name: Build and Test CGo App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Install Dependencies
        run: |
          # Enable universe repo
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update

          # Install build tools
          sudo apt-get install -y build-essential

          # Install the Makefile dependencies
          make deps

          # Finally, install dev headers
          sudo apt-get update
          sudo apt-get install -y \
            libunwind-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev

      - name: Build Pipeline Library
        run: |
          make build
