name: Build and Test CGo App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Install Dependencies
      run: |
        make deps

    - name: Build Pipeline Library
      run: |
        make build
        
    # - name: Test the application
    #   run: |
    #     make test